### ISSUE TITLE
fix qpdf error during package check()

### ISSUE THREAD

**Issue by katiesaund** [katiesaund/hogwash#42]
Getting this warning during check: 
‘qpdf’ is needed for checks on size reduction of PDFs

Internet says to (1) install qpdf executable and (2) make sure to run on r-hub and win-builder.

**Comment by katiesaund** [comment]
I've read that qpdf is a local executable that's necessary to be installed. I'll email flux support to see if it is installed anywhere.  If that doesn't work, switch to building package on local?

Other updates: 
rhub is package to test r packages. 
instructions: 
rhub::validate_email()
rhub::check_for_cran() 
Check_for_cran() "runs checks on platforms that are closest to platforms used by CRAN on submission:
Fedora Linux, R-devel, clang, gfortran,
Ubuntu Linux 16.04 LTS, R-release, GCC,
Windows Server 2008 R2 SP1, R-devel, 32⁄64 bit"

**Comment by katiesaund** [comment]
Other issues found while checking using rhub: 
 Namespaces in Imports field not imported from: 
‘geiger’ ‘ggplot2’ ‘grid’ ‘gridExtra’ ‘optparse’ ‘phangorn’ ‘truncnorm’
 All declared Imports should be used

**Comment by katiesaund** [comment]
qpdf is currently listed in DESCRIPTION suggests. If it's not actually an r package, remove it?

**Comment by katiesaund** [comment]
Based on other people's posts on the same issue: 

- If winbuilder doesn't list qpdf issue, it won't be an issue during CRAN submission. It's not on the run earlier today, so it's probably just a local problem.
-It might be an issue caused by running 3.5.0 instead of 3.6.1
-I did ask flux to install qpdf -- it they do I'll add the path to the dir and see if it helps.

**Comment by StatsGary** [comment]
I have a fix for this: https://newbedev.com/how-to-build-qpdf-on-windows. This might help you if you don't want the warnings to appear at all and have qpdf on your machine.
