### ISSUE TITLE
Add feature in hogwash where genotypes are printed to PDF by rank rather than by original order

### ISSUE THREAD

**Issue by katiesaund** [katiesaund/hogwash#62]

**Comment by Owuorgpo** [comment]
Awesome idea, ranking would make it easy to identify target genes. Slightly related to the PDF output would be additional output for the figures (genotype transition and the null distribution figures as images and not embedded in PDF).

**Comment by katiesaund** [comment]
Hogwash now plots genotypes in the output pdf by rank order. 

Genotypes are ranked by FDR-corrected P-values where ties are ordered by "first." When printing rank on the plot, however, ties are calculated as "average" rank.
