### ISSUE TITLE
Object must be a character string

### ISSUE THREAD

**Issue by Owuorgpo** [katiesaund/hogwash#64]
Hi,
This is an awesome program.
I have a small issue, I am trying to use hogwash for the first time but even the test runs in the vignettes give me this error:
"Error in check_is_string(name) : Object must be a character string"
I tried with my own data and I still get the same. Tried looking into the code but am not sure which input has the problem.
Thanks

**Comment by katiesaund** [comment]
I think the error is that the default file_name when running hogwash is a date not a character. I'll replace the default in the hogwash code. In the meantime, all you should need to avoid the error is to set file_name = "any_character_string_you_want". Please let me know if that fixes the issue or not.

**Comment by Owuorgpo** [comment]
Thanks, 
That sorted the issue. This will be fun.
Thanks

**Comment by katiesaund** [comment]
The default file_name has been replaced with the character string "hogwash." Now the examples in the wikis run without issue.
