### ISSUE TITLE
More updates on ancestral reconstruction (and other steps)

### ISSUE THREAD

**Issue by zenalapp** [katiesaund/hogwash#71]
To have an idea of how much progress is made.

e.g. give a notice every 100 or 1000 variants or something: ancestral reconstruction done on 100/5,000 variants, etc.

**Comment by katiesaund** [comment]
Hogwash v1.2.4 prints AR progress at 25%, 50%, 75%, and 100% complete. 

Example print statements:
"Ancestral reconstruction 25% complete: 2020-09-22 11:02:09"
"Ancestral reconstruction 50% complete: 2020-09-22 11:12:51"
"Ancestral reconstruction 75% complete: 2020-09-22 11:23:05"
"Ancestral reconstruction complete: 2020-09-22 11:35:10"
