### ISSUE TITLE
check_if_g_mat_can_be_plotted issue

### ISSUE THREAD

**Issue by annarerra** [katiesaund/hogwash#82]
Hello Katie!

I run hogwash and i received this error:
[1] "Ancestral reconstruction complete: 2021-04-23 12:54:56"
[1] "Permutation test complete: 2021-04-23 14:39:56"
Error in do.call("cbind", lapply(x, "is.na")) :
  variable names are limited to 10000 bytes
Calls: hogwash ... check_if_g_mat_can_be_plotted -> is.na -> is.na.data.frame -> do.call
Execution halted

I have already run hogwash in a smaller dataset, using similar names, so I think the names are not the issue.
I also checked my genotype matrix with the function check_if_g_mat_can_be_plotted and it can be plotted.

My datasets contains 992 samples, maybe the problem is that it is too big?

I would appreciate any help.

Thank you in advance.

Best regards,
Anna-Isavella

**Comment by katiesaund** [comment]
I generated genotypes and a phenotype of slightly larger sizes than in this problematic job and then ran them through the plotting function, particularly focusing on the function check_if_g_mat_can_be_plotted(). Unfortunately, I cannot replicate the error message so I can't figure out how to avoid the problem. 

Suggested workaround: 
You can break your genotype matrix into two smaller ones and run those separately through hogwash and then combine the output data objects (hit p-values, etc...) into one result.
