### ISSUE TITLE
Ability to take in NA

### ISSUE THREAD

**Issue by katiesaund** [katiesaund/hogwash#84]
Adapt it so hogwash can take genotypes or phenotypes with missing data.

**Comment by ksw9** [comment]
Hi @katiesaund, Thanks for a fantastic resource. I'm wondering if you have plans to update this so that hogwash can take NA values in the genotype/phenotype matrices? In the meantime, do you have suggestions for how to deal with this?

**Comment by katiesaund** [comment]
For my research I removed samples with missing phenotype data and removed SNPs missing data. Alternatively, you might try to impute the missing genotype or phenotype information. 

I am not actively adding features to hogwash - I only have the time to patch bugs as they arise. The code is open source so if anyone wants to implement the ability to accept NAs I would welcome that. 

Best of luck!

**Comment by ksw9** [comment]
Thanks so much for letting me know, Katie! Great to know all the code is available—thanks for all of your work on it.

All the best,
Katie

From: Katie Saund ***@***.***>
Date: Friday, October 28, 2022 at 11:18 AM
To: katiesaund/hogwash ***@***.***>
Cc: Katharine Walter ***@***.***>, Comment ***@***.***>
Subject: Re: [katiesaund/hogwash] Ability to take in NA (#84)

For my research I removed samples with missing phenotype data and removed SNPs missing data. Alternatively, you might try to impute the missing genotype or phenotype information.

I am not actively adding features to hogwash - I only have the time to patch bugs as they arise. The code is open source so if anyone wants to implement the ability to accept NAs I would welcome that.

Best of luck!
